feat: 3-sqlite-server
yukikamome316/webken-2024 pull request #1
Opened 2024-05-18 17:09 UTC by yukikamome316

SQLiteを使用した簡易的なTODOアプリサーバーを作る資料です。
`webken-2024/3-sqlite-server` に実装しています。

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-1-simple-sqlite-app/queries.js
前このクエリを別ファイルに切り出すみたいなことをやってたんだけど初心者からするとめちゃくちゃわかりにくそうなのでファイル直書きで最初やってあとでファイル切り出しみたいな演習を挟んだ方がいい気がしてるんだよね

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    });
```suggestion
    return c.json({ message: err.message }, {
      status: 400,
    });
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +  return new Response(null, { status: 204 });
```suggestion
  return c.body(null, { status: 204 });
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +  return new Response(null, { status: 204 });
```suggestion
  return c.body(null, { status: 204 });
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +      });
```suggestion
      return c.json({ message: err.message }, {
        status: 400,
      });
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +      });
```suggestion
      return c.json({ message: err.message }, {
        status: 400,
      });
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    });
```suggestion
    return c.json({ message: err.message }, {
      status: 400,
    });
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +  });
```suggestion
  return c.json(tasks);
```

2024-05-19 12:16 UTC, sor4chi commented on 3-sqlite-server/3-1-simple-sqlite-app/server.js
> +import sqlite3 from "sqlite3";
better-sqlite3に変えない？

2024-05-20 03:04 UTC, sor4chi requested changes

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-2-alter-tasks/queries.js
> +export const Tasks = {
```suggestion
export const TaskQuery = {
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-2-alter-tasks/server.js
> +import * as queries from "./queries.js";
```suggestion
import { TaskQuery } from "./queries.js";
```

* alias import 使う前に named import にした方がいいかも
named import 飛び越えてちゃうとどういう構造で queries を呼べてるかわからなくなりそうなので

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-2-alter-tasks/server.js
> +}
これいる？
暗黙強制的に削除されちゃうの良くない気がするのでリセットしたい時は手動で`test.db`消しましょうねでいい気がしてる

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-2-alter-tasks/server.js
> +};
そもそもこのファイルのDB宣言の下にこの関数定義するなら引数にdbいらなくない？
```suggestion
const displayAllTasks = (title) => {
  const rows = db.prepare(queries.Tasks.readAll).all();
  console.log(`---- ${title} ----`);
  rows.forEach((row) => {
    console.log(`${row.id}: ${row.title} (completed: ${row.completed})`);
  });
  console.log();
};
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-2-alter-tasks/server.js
> +})();
もうtransaction教える？
普通に直列に大域に定義の方がわかりやすいから混乱しなくてすみそうだなと思ったけど

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    return c.body(null, { status: 201 });
```suggestion
    return c.body(null, 201);
```
ごめんこれで良くなったんだった

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    );
ditto
```suggestion
    return c.json({ message: err.message }, 400);
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    );
ditto
```suggestion
    return c.json({ message: err.message }, 400);
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +  return c.body(null, { status: 204 });
ditto
```suggestion
  return c.body(null, 204);
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    );
ditto
```suggestion
    return c.json({ message: err.message }, 400);
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +    return c.body(null, { status: 204 });
ditto
```suggestion
    return c.body(null, 204);
```

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-2-alter-tasks/server.js
> +  db.prepare(queries.Tasks.create).run("ICPCに参加する", "0");
bool値の引数が文字列の01より数値の01の方がわかりやすいと思ったんだけどどう？
下も同じく

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +todo.put("/:id", async (c) => {
このAPIだとparam.titleがない場合は204が返ってくるの？
400 Invalid Requestがいいと思うんだけど

2024-05-20 03:04 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
というか思ったけど204返すの良くないかも
200 Successfully Createdとか
何かしら反応あった方がデバッグしやすいし設計的にも正しいと思う

2024-05-20 05:22 UTC, batora9 commented
そらちさんの修正したら見ます

2024-05-20 07:54 UTC, yukikamome316 commented on 3-sqlite-server/3-2-alter-tasks/server.js
> +})();
> 普通に直列に大域に定義

これはどういう意味でしょうか？

2024-05-20 09:26 UTC, yukikamome316 commented on 3-sqlite-server/3-3-todo-api/server.js
> +todo.put("/:id", async (c) => {
param.completed のみ存在する場合でも更新できるAPIにしています
どっちもない場合は 400 にしたいと思います

2024-05-20 20:28 UTC, sor4chi requested changes

2024-05-20 20:28 UTC, sor4chi commented on 1-simple-server-app/1-5-hono-routing/server.js
> +todo.get("/:date{[0-9]+}/:title{[a-z]+}", (c) => {
これ講習でやる予定なん？こんな複雑なルーティング使うことそんなないからわざわざ教える必要なくない？

2024-05-20 20:28 UTC, sor4chi commented on 1-simple-server-app/1-4-get-todo/server.js
> +    id: String(Number(todoList.length === 0 ? "1" : todoList[todoList.length - 1].id) + 1),
この部分明らかに汚くなってしまってるので大域にcurrentIdみたいなインクリメント用のlet数値の変数作ればいいと思う
これ以降もすべて

2024-05-20 20:28 UTC, sor4chi commented on 1-simple-server-app/1-4-get-todo/server.js
>    const param = await c.req.json();
param.titleとparam.completedない時も作成されちゃいそう

2024-05-20 20:28 UTC, sor4chi commented on 1-simple-server-app/1-5-hono-routing/server.js
そもそもappとtodo分ける必要なくない？
group routing教えるの余計だと思うんだよね
これ以降もすべて

2024-05-20 20:28 UTC, sor4chi commented on 1-simple-server-app/1-6-edit-todo/server.js
> +  if (param.title !== undefined) {
33行目ではtitleをnull値で見てる(undefinedの他に空文字列もアウトにしてる)のに、37行目ではundefinedだけをみててどっちかに統一した方が良さそう？
これ以降も全て

2024-05-20 20:28 UTC, sor4chi commented on 1-simple-server-app/1-6-edit-todo/server.js
>    const newTodo = {
ここはバリデーションない？

2024-05-20 20:28 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/README.md
> +```
これは治すの？

2024-05-20 20:28 UTC, sor4chi commented on 3-sqlite-server/3-3-todo-api/server.js
> +  const param = await c.req.json();
バリデーションなくていいの？

2024-05-20 20:28 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
これ一気に書くの？
サーバーとクライアントを一対一対応で機能追加してった方がいい気がしたので

2024-05-20 20:28 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
これどうにかしたいなー

2024-05-20 20:28 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +});
api使ってるならform使う必要なくない？
~~本当は全てformのMPAであって欲しいけど~~

2024-05-21 04:03 UTC, yukikamome316 commented on 1-simple-server-app/1-4-get-todo/server.js
>    const param = await c.req.json();
completedが無い場合はfalseで作成するようにします
param.titleはboolにキャストしてfalseでないことをチェックするように変更します

2024-05-21 04:17 UTC, yukikamome316 commented on 1-simple-server-app/1-5-hono-routing/server.js
group routingを使わないようにした場合でも、エンドポイントは `todo/api` にしておきますか？

2024-05-21 05:37 UTC, yukikamome316 commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
どんな感じで綺麗にしますか？

2024-05-21 08:52 UTC, yukikamome316 commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
クライアントの処理は `2-client-api-call/2-5-styled-todo-app` で書いた前提ですので、使いまわしています

2024-05-21 20:14 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
```js
const input = document.createElement("input");
input.type = "checkbox";
input.checked = todo.completed;
input.addEventListener("change", function () {
  updateTodoStatus(todo.id, this.checked);
});
const textbox = document.createElement("input");
textbox.type = "text";
textbox.value = todo.title;
textbox.classList.add("task-textbox");
textbox.addEventListener("change", function () {
  updateTodoTitle(todo.id, this.value);
});
const button = document.createElement("button");
button.textContent = "削除";
button.classList.add("delete-button");
button.addEventListener("click", function () {
  deleteTodo(todo.id);
});

const todoElement = document.createElement("div");
todoElement.appendChild(input);
todoElement.appendChild(textbox);
todoElement.appendChild(button);
todoListElement.appendChild(todoElement);
```
書いてみたけどわかりやすさと引き換えに結構長くなっちゃったな

2024-05-22 03:01 UTC, yukikamome316 commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
やはりそうするしかないんですね
どっちがいいと思いますか？

2024-05-22 03:57 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
どういう要素を作っているのかコメントつけながらならいいんじゃない？

2024-05-22 04:01 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
```js
// <input />
const input = document.createElement("input");
// <input type="checkbox" />
input.type = "checkbox";
// <input type="checkbox" checked />
input.checked = todo.completed;
// <input type="checkbox" checked onchange="..."/>
input.addEventListener("change", function () {
  updateTodoStatus(todo.id, this.checked);
});

// <input />
const textbox = document.createElement("input");
// <input type="text" />
textbox.type = "text";
// <input type="text" value="..." />
textbox.value = todo.title;
// <input type="text" value="..." class="task-textbox" />
textbox.classList.add("task-textbox");
// <input type="text" value="..." class="task-textbox" onchange="..." />
textbox.addEventListener("change", function () {
  updateTodoTitle(todo.id, this.value);
});

// <button></button>
const button = document.createElement("button");
// <button>削除</button>
button.textContent = "削除";
// <button class="delete-button">削除</button>
button.classList.add("delete-button");
// <button class="delete-button" onclick="">削除</button>
button.addEventListener("click", function () {
  deleteTodo(todo.id);
});

// <div></div>
const todoElement = document.createElement("div");
// <div><input ... /></div>
todoElement.appendChild(input);
// <div><input ... /><input ... /></div>
todoElement.appendChild(textbox);
// <div><input ... /><input ... /><button>削除</button></div>
todoElement.appendChild(button);
todoListElement.appendChild(todoElement);
```

2024-05-22 04:02 UTC, sor4chi commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
結局JSをそのまま書くのって辛いよねっていう感覚を理解して欲しいだけだから長くなる分にはしょうがないと思ってるけど、文字列組立は流石にハードル高そうという感じ

2024-05-22 04:04 UTC, yukikamome316 commented on 3-sqlite-server/3-4-sqlite-todo-app/client/index.js
> +    `;
わかりました！

2024-05-24 09:44 UTC, sor4chi commented
自分一通り見たのでつぎ他の人レビューお願いしてもいいかな？
@batora9 @a01sa01to

2024-05-24 09:58 UTC, a01sa01to commented on 1-simple-server-app/1-4-get-todo/server.js
> +    completed: param.completed ? 1 : 0,
DB に入れるところじゃないけどこれって 01 でいいの？ (ほかのところも)

2024-05-24 09:58 UTC, a01sa01to commented on 3-sqlite-server/3-3-todo-api/server.js
> +    const updateTitleResult = updateTitleStmt.run(param.title, id);
この条件って正しい？

2024-05-24 09:58 UTC, a01sa01to commented on 3-sqlite-server/3-4-sqlite-todo-app/client/style.css
> +@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&display=swap");
いらなそう？

2024-05-24 09:58 UTC, a01sa01to commented on 3-sqlite-server/3-4-sqlite-todo-app/client/style.css
> +html[lang="ja"] {
`[lang="ja"]` ついてるの理由ある？

2024-05-24 10:14 UTC, yukikamome316 commented on 3-sqlite-server/3-3-todo-api/server.js
> +    const updateTitleResult = updateTitleStmt.run(param.title, id);
間違ってます！
修正しきれていませんでしたので、直します！

2024-05-24 11:05 UTC, a01sa01to commented on 1-simple-server-app/1-5-hono-routing/server.js
> +app.get("/api/todo/:id", (c) => c.json("入力されたID: " + c.req.param("id"), 200));
これ json か？

2024-05-24 11:05 UTC, a01sa01to commented on 1-simple-server-app/1-4-get-todo/server.js
>    const newTodo = {
```suggestion
  }

  const newTodo = {
```

2024-05-24 11:05 UTC, a01sa01to commented on 1-simple-server-app/1-4-get-todo/server.js
> +  todoList.push(newTodo);
```suggestion

  todoList.push(newTodo);
```

2024-05-24 11:05 UTC, a01sa01to commented on 1-simple-server-app/1-6-edit-todo/server.js
> +  if (param.title) {
```suggestion

  if (param.title) {
```

2024-05-24 11:05 UTC, a01sa01to commented on 1-simple-server-app/1-6-edit-todo/server.js
>    todoList = todoList.filter((todo) => todo.id !== id);
`todoList` const にしてない？

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-2-display-todo/server/server.js
>  let todoList = [
const?

2024-05-24 11:05 UTC, a01sa01to commented on 1-simple-server-app/1-6-edit-todo/server.js
> +    todo.completed = param.completed;
一応型検証しなくてだいじょうぶ？ (ほかのところも)

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-3-complete-task/server/server.js
> +  if (param.title) {
```suggestion
  }

  if (param.title) {
```

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-4-simple-todo-app/server/server.js
> +
```suggestion
  }

```

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-4-simple-todo-app/server/server.js
> +  todoList.push(newTodo);
```suggestion

  todoList.push(newTodo);
```

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-4-simple-todo-app/server/server.js
> +
```suggestion
  }

```

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-5-styled-todo-app/server/server.js
> +
```suggestion
  }

```

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-5-styled-todo-app/server/server.js
> +  todoList.push(newTodo);
```suggestion

  todoList.push(newTodo);
```

2024-05-24 11:05 UTC, a01sa01to commented on 2-client-api-call/2-5-styled-todo-app/server/server.js
> +
```suggestion
  }

```

2024-05-25 10:13 UTC, batora9 commented
ごめんなさい。まだ見れてません

2024-05-25 16:52 UTC, batora9 commented
`1-simple-server-app/1-2-first-http-server`で
```bash
node server.js
```
を実行するときのエラーです

```bash
(node:10924) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/batora/Programs/webken-mocks/webken-2024/1-simple-server-app/1-2-first-http-server/server.js:1
import http from 'http';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
```

2024-05-25 17:22 UTC, yukikamome316 commented on 1-simple-server-app/1-6-edit-todo/server.js
> +    todo.completed = param.completed;
`typeof param.completed === "boolean"` で検証するってことですか？

2024-05-25 17:27 UTC, yukikamome316 commented
> `1-simple-server-app/1-2-first-http-server`で
> 
> ```shell
> node server.js
> ```
> 
> を実行するときのエラーです
> 
> ```shell
> (node:10924) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> /home/batora/Programs/webken-mocks/webken-2024/1-simple-server-app/1-2-first-http-server/server.js:1
> import http from 'http';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at internalCompileFunction (node:internal/vm:128:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1280:20)
>     at Module._compile (node:internal/modules/cjs/loader:1332:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
>     at Module.load (node:internal/modules/cjs/loader:1206:32)
>     at Module._load (node:internal/modules/cjs/loader:1022:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
>     at node:internal/main/run_main_module:28:49
> 
> Node.js v20.12.2
> ```

@sor4chi @a01sa01to 
序盤の内容ではpackage.jsonを使わずに直接 `node` コマンドで実行しているのですが、
ESModuleの記法を使うためには拡張子を.mjsにすればいいですか？
それともpackage.jsonを作って、 `"type": "module"` を追加した方がいいですか？

2024-05-25 18:44 UTC, batora9 commented
> > `1-simple-server-app/1-2-first-http-server`で
> > ```shell
> > node server.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > を実行するときのエラーです
> > ```shell
> > (node:10924) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > /home/batora/Programs/webken-mocks/webken-2024/1-simple-server-app/1-2-first-http-server/server.js:1
> > import http from 'http';
> > ^^^^^^
> > 
> > SyntaxError: Cannot use import statement outside a module
> >     at internalCompileFunction (node:internal/vm:128:18)
> >     at wrapSafe (node:internal/modules/cjs/loader:1280:20)
> >     at Module._compile (node:internal/modules/cjs/loader:1332:27)
> >     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
> >     at Module.load (node:internal/modules/cjs/loader:1206:32)
> >     at Module._load (node:internal/modules/cjs/loader:1022:12)
> >     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
> >     at node:internal/main/run_main_module:28:49
> > 
> > Node.js v20.12.2
> > ```
> 
> @sor4chi @a01sa01to 序盤の内容ではpackage.jsonを使わずに直接 `node` コマンドで実行しているのですが、 ESModuleの記法を使うためには拡張子を.mjsにすればいいですか？ それともpackage.jsonを作って、 `"type": "module"` を追加した方がいいですか？

自分は今後`package.json`使うことを考えたら後者の方がよさそうだとおもいます。

2024-05-26 00:19 UTC, sor4chi commented
package.jsonの形にしようか、例の最小限構成のpackage.jsonだけであればそこまでつまづきはないはず...

2024-05-26 00:20 UTC, sor4chi commented on 1-simple-server-app/1-6-edit-todo/server.js
> +    todo.completed = param.completed;
複雑すぎるの良くないのでなるべくシンプルで情報量少なくしていきたい

2024-05-26 06:03 UTC, yukikamome316 commented on 1-simple-server-app/1-6-edit-todo/server.js
> +    todo.completed = param.completed;
1-6-edit-todoの段階では、まだ厳密な型検証は扱わないで、Reactの基礎を終えたあたりで徐々に扱っていくのはどうですか？

2024-05-30 04:14 UTC, a01sa01to commented on 1-simple-server-app/1-2-first-http-server/README.md
> +## 1-3-first-hono-app
これ 1-3 なのは正しい？

2024-05-31 22:21 UTC, batora9 commented
次回できれば`1-4-get-todo`やろうと思うのですがいきなりhonoで書くのはちょっと早すぎかなと思いますがどうでしょうか？

2024-06-01 19:05 UTC, yukikamome316 commented
> 次回できれば`1-4-get-todo`やろうと思うのですがいきなりhonoで書くのはちょっと早すぎかなと思いますがどうでしょうか？

@batora9 
Honoだからこそ簡単に書けるから、初学者にとって分かりやすいと思う

2024-06-02 00:53 UTC, sor4chi commented
@batora9 
```ts
const http = require('http');
const { StringDecoder } = require('string_decoder');

const todoList = [
  { title: 'JavaScriptを勉強する', completed: false },
  { title: 'TODOアプリを自作する', completed: false },
  { title: '漫画を読み切る', completed: true },
  { title: 'ゲームをクリアする', completed: false },
];

const server = http.createServer((req, res) => {
  const decoder = new StringDecoder('utf-8');
  let buffer = '';

  req.on('data', (data) => {
    buffer += decoder.write(data);
  });

  req.on('end', () => {
    buffer += decoder.end();

    const headers = {
      'Content-Type': 'application/json',
    };

    if (req.method === 'GET' && req.url === '/') {
      res.writeHead(200, headers);
      res.end(JSON.stringify(todoList));
    } else if (req.method === 'POST' && req.url === '/') {
      try {
        const data = JSON.parse(buffer);
        if (!data.title) {
          throw new Error('Title must be provided');
        }

        const newTodo = {
          title: data.title,
          completed: !!data.completed,
        };

        todoList.push(newTodo);
        res.writeHead(200, headers);
        res.end(JSON.stringify({ message: 'Successfully created' }));
      } catch (err) {
        res.writeHead(400, headers);
        res.end(JSON.stringify({ message: err.message }));
      }
    } else {
      res.writeHead(404, headers);
      res.end(JSON.stringify({ message: 'Not Found' }));
    }
  });
});

server.listen(8000, () => {
  console.log('Server running on port 8000');
});
```

ちなみに Hono 使わないで Node.js オンリーで書くとこんな感じ

2024-06-05 02:59 UTC, yukikamome316 commented
@batora9 
`1-simple-server-app/1-3-get-todo-http` を追加したよー

2024-06-20 09:05 UTC, batora9 requested changes

2024-06-20 09:05 UTC, batora9 commented on 2-client-api-call/2-1-first-api-call/README.md
>  `2-client-api-call/2-1-first-api-call` に `cd` した上で、以下のコマンドを実行する必要があります:
```suggestion
`2-client-api-call/2-1-first-api-call/server` に `cd` した上で、以下のコマンドを実行する必要があります:
```

2024-06-23 06:56 UTC, sor4chi requested changes
`npm start`って書いてるとこ、`npm run start`じゃないと動かなくない？

2024-06-24 21:33 UTC, sor4chi approved these changes

2024-06-25 00:21 UTC, batora9 approved these changes

2024-06-25 04:06 UTC, merged